# filename: docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - qdrant
    environment:
      - ALLOW_ORIGINS=*
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-large
      - EMBEDDING_DIMENSIONS=1024
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=products
      - QDRANT_CHAT_COLLECTION_NAME=chats
      - DOCS_DIR=data/docs
      - EXPORT_DIR=data
    ports:
      - "8000:8000"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: