version: '3.8'

services:
  app:
    build: .
    depends_on:
      - qdrant
    environment:
      - ALLOW_ORIGINS
      - OPENAI_API_KEY
      - MODEL
      - EMBEDDING_MODEL
      - EMBEDDING_DIMENSIONS
      - QDRANT_HOST
      - QDRANT_PORT
      - QDRANT_COLLECTION_NAME
      - QDRANT_CHAT_COLLECTION_NAME
      - DOCS_DIR
      - EXPORT_DIR

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

volumes:
  qdrant_data: